fix: pre-push iterates over string of commands

diff --git a/client/.husky/pre-push b/client/.husky/pre-push
--- a/client/.husky/pre-push
+++ b/client/.husky/pre-push
@@ -7,6 +7,7 @@ GREEN="\033[1;32m"
 NC="\033[0m"
 
 ROOT_PROJECT_DIR="${PWD}"
+npmCommands="prettier lint test"
 apps="client server"
 modifiedApps=""
 
@@ -30,16 +31,22 @@ if [ -z "$modifiedApps" ]; then
     exit 0
 fi
 
-# Loop through each modified app and run Prettier check and tests
-for app in $modifiedApps; do
-    cd "${ROOT_PROJECT_DIR}/${app}"  # Navigate to the app directory
-    echo "${BLUE}Running prettier styling check for the ${app}${NC}"
-    if ! npm run prettier:check; then
-        echo "${RED}The prettier styling check failed for the ${app}. Run 'npm run prettier:fix' on the ${app}${NC}"
+# Function to run checks or tests
+run_command() {
+    local app=$1
+    local command=$2
+    cd "${ROOT_PROJECT_DIR}/${app}"
+    echo "${BLUE}Running ${command} for the ${app}${NC}"
+    if ! npm run "${command}"; then
+        echo "${RED}The ${command} failed for the ${app}. Please fix the issues in the ${app}${NC}"
         exit 1
     fi
-    echo "${GREEN}Prettier check ran successfully for the ${app}${NC}"
-    echo "${BLUE}Running ${app} tests${NC}"
-    npm run test
-    echo "${GREEN}The tests ran successfully for the ${app}${NC}"
+    echo "${GREEN}The \`npm run ${command}\` command ran successfully for the ${app}${NC}"
+}
+
+# Loop through each modified app and run checks
+for app in $modifiedApps; do
+    for command in $npmCommands; do
+        run_command "${app}" "${command}"
+    done
 done
